GET {{endpoint}}/todos

###

GET {{endpoint}}/todos/65ab56ea679e851a94685808

###

POST {{endpoint}}/todos
Content-Type: application/json

{
  "title": "Foo Bar"
}

###

DELETE {{endpoint}}/todos/65ab56f0679e851a9468580a

###

PUT {{endpoint}}/todos/65ab56ea679e851a94685808
Content-Type: application/json

{
  "title": "Baz Qux",
  "completed": true
}